# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Summary(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, sp_host=None, engine_name=None, dump=None):  # noqa: E501
        """Summary - a model defined in OpenAPI

        :param sp_host: The sp_host of this Summary.  # noqa: E501
        :type sp_host: str
        :param engine_name: The engine_name of this Summary.  # noqa: E501
        :type engine_name: str
        :param dump: The dump of this Summary.  # noqa: E501
        :type dump: Dict[str, int]
        """
        self.openapi_types = {
            'sp_host': str,
            'engine_name': str,
            'dump': Dict[str, int]
        }

        self.attribute_map = {
            'sp_host': 'sp_host',
            'engine_name': 'engine_name',
            'dump': 'dump'
        }

        self._sp_host = sp_host
        self._engine_name = engine_name
        self._dump = dump

    @classmethod
    def from_dict(cls, dikt) -> 'Summary':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Summary of this Summary.  # noqa: E501
        :rtype: Summary
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sp_host(self):
        """Gets the sp_host of this Summary.


        :return: The sp_host of this Summary.
        :rtype: str
        """
        return self._sp_host

    @sp_host.setter
    def sp_host(self, sp_host):
        """Sets the sp_host of this Summary.


        :param sp_host: The sp_host of this Summary.
        :type sp_host: str
        """

        self._sp_host = sp_host

    @property
    def engine_name(self):
        """Gets the engine_name of this Summary.


        :return: The engine_name of this Summary.
        :rtype: str
        """
        return self._engine_name

    @engine_name.setter
    def engine_name(self, engine_name):
        """Sets the engine_name of this Summary.


        :param engine_name: The engine_name of this Summary.
        :type engine_name: str
        """

        self._engine_name = engine_name

    @property
    def dump(self):
        """Gets the dump of this Summary.


        :return: The dump of this Summary.
        :rtype: Dict[str, int]
        """
        return self._dump

    @dump.setter
    def dump(self, dump):
        """Sets the dump of this Summary.


        :param dump: The dump of this Summary.
        :type dump: Dict[str, int]
        """

        self._dump = dump
