# coding: utf-8

"""
    Kearch specialist search engine gateway API

    Kearch specialist search engine gateway API  # noqa: E501

    OpenAPI spec version: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.summary import Summary  # noqa: E501
from openapi_client.rest import ApiException


class TestSummary(unittest.TestCase):
    """Summary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSummary(self):
        """Test Summary"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.summary.Summary()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
