# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ConnectionRequestOnME(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, sp_host=None, engine_name=None, scheme=None):  # noqa: E501
        """ConnectionRequestOnME - a model defined in OpenAPI

        :param sp_host: The sp_host of this ConnectionRequestOnME.  # noqa: E501
        :type sp_host: str
        :param engine_name: The engine_name of this ConnectionRequestOnME.  # noqa: E501
        :type engine_name: str
        :param scheme: The scheme of this ConnectionRequestOnME.  # noqa: E501
        :type scheme: str
        """
        self.openapi_types = {
            'sp_host': str,
            'engine_name': str,
            'scheme': str
        }

        self.attribute_map = {
            'sp_host': 'sp_host',
            'engine_name': 'engine_name',
            'scheme': 'scheme'
        }

        self._sp_host = sp_host
        self._engine_name = engine_name
        self._scheme = scheme

    @classmethod
    def from_dict(cls, dikt) -> 'ConnectionRequestOnME':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ConnectionRequestOnME of this ConnectionRequestOnME.  # noqa: E501
        :rtype: ConnectionRequestOnME
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sp_host(self):
        """Gets the sp_host of this ConnectionRequestOnME.


        :return: The sp_host of this ConnectionRequestOnME.
        :rtype: str
        """
        return self._sp_host

    @sp_host.setter
    def sp_host(self, sp_host):
        """Sets the sp_host of this ConnectionRequestOnME.


        :param sp_host: The sp_host of this ConnectionRequestOnME.
        :type sp_host: str
        """

        self._sp_host = sp_host

    @property
    def engine_name(self):
        """Gets the engine_name of this ConnectionRequestOnME.


        :return: The engine_name of this ConnectionRequestOnME.
        :rtype: str
        """
        return self._engine_name

    @engine_name.setter
    def engine_name(self, engine_name):
        """Sets the engine_name of this ConnectionRequestOnME.


        :param engine_name: The engine_name of this ConnectionRequestOnME.
        :type engine_name: str
        """

        self._engine_name = engine_name

    @property
    def scheme(self):
        """Gets the scheme of this ConnectionRequestOnME.


        :return: The scheme of this ConnectionRequestOnME.
        :rtype: str
        """
        return self._scheme

    @scheme.setter
    def scheme(self, scheme):
        """Sets the scheme of this ConnectionRequestOnME.


        :param scheme: The scheme of this ConnectionRequestOnME.
        :type scheme: str
        """

        self._scheme = scheme
