# coding: utf-8

"""
    Kearch meta search engine gateway API

    Kearch meta search engine gateway API  # noqa: E501

    OpenAPI spec version: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_a_conenction_request_post(self):
        """Test case for add_a_conenction_request_post

        Add a connection request sent from specialist server to meta server.  # noqa: E501
        """
        pass

    def test_add_a_summary_post(self):
        """Test case for add_a_summary_post

        Add a summary to meta server.  # noqa: E501
        """
        pass

    def test_delete_a_conenction_request_delete(self):
        """Test case for delete_a_conenction_request_delete

        Delete a connection request sent from specialist server to this meta server.  # noqa: E501
        """
        pass

    def test_retrieve_get(self):
        """Test case for retrieve_get

        Retrieve search results.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
