# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, sp_host=None, engine_name=None):  # noqa: E501
        """InlineResponse200 - a model defined in OpenAPI

        :param sp_host: The sp_host of this InlineResponse200.  # noqa: E501
        :type sp_host: str
        :param engine_name: The engine_name of this InlineResponse200.  # noqa: E501
        :type engine_name: str
        """
        self.openapi_types = {
            'sp_host': str,
            'engine_name': str
        }

        self.attribute_map = {
            'sp_host': 'sp_host',
            'engine_name': 'engine_name'
        }

        self._sp_host = sp_host
        self._engine_name = engine_name

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sp_host(self):
        """Gets the sp_host of this InlineResponse200.


        :return: The sp_host of this InlineResponse200.
        :rtype: str
        """
        return self._sp_host

    @sp_host.setter
    def sp_host(self, sp_host):
        """Sets the sp_host of this InlineResponse200.


        :param sp_host: The sp_host of this InlineResponse200.
        :type sp_host: str
        """

        self._sp_host = sp_host

    @property
    def engine_name(self):
        """Gets the engine_name of this InlineResponse200.


        :return: The engine_name of this InlineResponse200.
        :rtype: str
        """
        return self._engine_name

    @engine_name.setter
    def engine_name(self, engine_name):
        """Sets the engine_name of this InlineResponse200.


        :param engine_name: The engine_name of this InlineResponse200.
        :type engine_name: str
        """

        self._engine_name = engine_name
