# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, sp_host=None):  # noqa: E501
        """InlineResponse2001 - a model defined in OpenAPI

        :param sp_host: The sp_host of this InlineResponse2001.  # noqa: E501
        :type sp_host: str
        """
        self.openapi_types = {
            'sp_host': str
        }

        self.attribute_map = {
            'sp_host': 'sp_host'
        }

        self._sp_host = sp_host

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sp_host(self):
        """Gets the sp_host of this InlineResponse2001.


        :return: The sp_host of this InlineResponse2001.
        :rtype: str
        """
        return self._sp_host

    @sp_host.setter
    def sp_host(self, sp_host):
        """Sets the sp_host of this InlineResponse2001.


        :param sp_host: The sp_host of this InlineResponse2001.
        :type sp_host: str
        """

        self._sp_host = sp_host
